export const FETCH_LOCATION_REQUEST = "FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const USER_SINGUP_SUCCESS = "USER_SINGUP_SUCCESS"
export const USER_SINGUP_FAILURE = "USER_SINGUP_FAILURE"

export const SEARCH_TEXT = "SEARCH_TEXT"

export const USER_LOGOUT = "USER_LOGOUT"